// Product Data
export const productData = [
    {
      id: 1,
      name: "Black Pants",
      category: "Apparel",
      price: 99.99,
      imageUrl: 'product-image-1.png',
      productRating: 4.2,
      description: "Some really nice pants",
    },
    {
      id: 1,
      name: "Black Pants",
      category: "Apparel",
      price: 99.99,
      imageUrl: 'product-image-1.png',
      productRating: 4.2,
      description: "Some really nice pants",
    },
    {
      id: 1,
      name: "Black Pants",
      category: "Apparel",
      price: 99.99,
      imageUrl: 'product-image-1.png',
      productRating: 4.2,
      description: "Some really nice pants",
    },
    {
      id: 1,
      name: "Black Pants",
      category: "Apparel",
      price: 99.99,
      imageUrl: 'product-image-1.png',
      productRating: 4.2,
      description: "Some really nice pants",
    },
    {
      id: 1,
      name: "Black Pants",
      category: "Apparel",
      price: 99.99,
      imageUrl: 'product-image-1.png',
      productRating: 4.2,
      description: "Some really nice pants",
    },
    {
      id: 1,
      name: "Black Pants",
      category: "Apparel",
      price: 99.99,
      imageUrl: 'product-image-1.png',
      productRating: 4.2,
      description: "Some really nice pants",
    },
    {
      id: 1,
      name: "Black Pants",
      category: "Apparel",
      price: 99.99,
      imageUrl: 'product-image-1.png',
      productRating: 4.2,
      description: "Some really nice pants",
    },
    {
      id: 123,
      name: "Black Pants",
      category: "Apparel",
      price: 99.99,
      imageUrl: 'product-image-1.png',
      productRating: 4.2,
      description: "Some really nice pants",
    },
  ];